### PR TITLE
Implement JS target (experimental)

### PR DESCRIPTION
**Pull request by krzema12**
This change provides a working JS version of kaml (tested through a separate demo consumer Gradle module).

However, it's not yet ready to be shipped because:

* the Maven Central publishing is likely to require an adjustment. We've recently configured it for [snakeyaml-engine-kmp](https://github.com/krzema12/snakeyaml-engine-kmp)
* there's a problem with running JS unit tests
  * `DescribeSpec` seems to be unsupported by the JS target
* missing unit tests for the JS-specific parts

### CODE REVIEW

**Comment by charleskorn** [comment]
Thanks for the PR @krzema12!

A couple of notes / questions:

* I don't have time to finish this myself, and I also have no experience with Kotlin/JS, but I'm happy to provide support / feedback to anyone that's keen
* If `snakeyaml-engine-kmp` supports the JVM as well, it'd be great to use it for the JVM, as that would significantly reduce the amount of platform-specific code
* Can you elaborate on "the Maven Central publishing is likely to require an adjustment"? As far as I'm aware, it should Just Work™️ 
* What's the issue with running nested tests on JS? Can this be fixed in Kotest?

**Comment by krzema12** [comment]
> If `snakeyaml-engine-kmp` supports the JVM as well, it'd be great to use it for the JVM, as that would significantly reduce the amount of platform-specific code
 
 Long-term, I'm totally for it as well, but for now our KMP port is yet immature and using it already for the JVM could introduce some regressions. That's why I propose to depend on `snakeyaml-engine-kmp` for the JS target for the beginning, let it stabilize a bit, and in the longer term, switch completely to `snakeyaml-engine-kmp`.
 
 > Can you elaborate on "the Maven Central publishing is likely to require an adjustment"? As far as I'm aware, it should Just Work™️
 
 I just remember from my early days of experimenting with KMP that publication to Maven Central required some fancy hacks, but indeed looking at kaml's build logic, it doesn't mention anything Java-specific - indeed it may just work! It would be a matter of trying it out in practice.
 
 > What's the issue with running nested tests on JS? Can this be fixed in Kotest?
 
 See the Gradle log:
 
 ```
 > Task :jsNodeTest
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlExceptionTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlListTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlMapTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlNodeTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlNullTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlPathTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlReadingTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlScalarTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlTaggedNodeTest' has been marked as ignored
 WARN: kotest-js only supports top level tests due to underlying platform limitations. 'YamlWritingTest' has been marked as ignored
 ```
 
 It comes from [this place in kotest](https://github.com/kotest/kotest/blob/71c1826e5b404359ad8efe7cd360a2db3af5436b/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/spec/interceptor/IgnoreNestedSpecStylesInterceptor.kt#L47). I'm not sure yet if it's better to somehow rewrite the tests in kaml or improve kotest.
 
 --------
 
 Given the above and our limited bandwidth, maybe it's fine with you to just consider merging this PR in the current form, getting some exposure for the new target and applying fixes as needed? Just be sure to review the changes in the common Kotlin code as they affect the JVM target as well.

**Comment by russellbanks** [comment]
> It comes from [this place in kotest](https://github.com/kotest/kotest/blob/71c1826e5b404359ad8efe7cd360a2db3af5436b/kotest-framework/kotest-framework-engine/src/commonMain/kotlin/io/kotest/engine/spec/interceptor/IgnoreNestedSpecStylesInterceptor.kt#L47). I'm not sure yet if it's better to somehow rewrite the tests in kaml or improve kotest.

https://github.com/charleskorn/kaml/issues/27#issuecomment-1540530440
https://github.com/charleskorn/kaml/pull/431

**Comment by krzema12** [comment]
@russellbanks cool, I guess we could revive your PR #431!

**Comment by charleskorn** [comment]
#431 is merged, thanks for your patience!

I'm happy to merge this once the merge conflict is resolved - could you please also add a note to the readme that makes it super clear that JS support is very experimental, untested, likely to break / change etc.?

**Comment by krzema12** [comment]
@charleskorn cool, I've just updated the PR, please review!

**Pull request merged**
