### PR TITLE
fix: `Decoder` does not represent the current node correctly

### PR DESCRIPTION
**Pull request by Jojo4GH**
First bug from https://github.com/charleskorn/kaml/pull/607

> Previously the `node` property on the decoders was not traversed in deep YAML trees (e.g. with `YamlMapLikeInputBase` and `YamlListInput`). This behaviour is different from the JSON serialization library and makes it impossible to implement a content based polymorphic `KSerializer` in a meaningful way without knowing of the whole YAML tree. See also the `DecodingFromYamlNodeSerializer` in `YamlReadingTest.kt` for an affected case

### CODE REVIEW

**Review by charleskorn — COMMENTED** [review]
Could you please add a test that demonstrates the issue this PR is trying to fix?

**Comment by Jojo4GH** [comment]
> Could you please add a test that demonstrates the issue this PR is trying to fix?

There is the change in YamlReadingTest that gets fixed by this PR. Should I add more?

**Comment by charleskorn** [comment]
> > Could you please add a test that demonstrates the issue this PR is trying to fix?
> 
> There is the change in YamlReadingTest that gets fixed by this PR. Should I add more?

It's not clear to me how the two changes are related, so yes: please add a simple test case that shows the issue and how this fixes it.

**Comment by charleskorn** [comment]
Thanks @Jojo4GH!

**Pull request merged**
