### PR TITLE
More elegant way to call the library's API

### PR DESCRIPTION
**Pull request by akuleshov7**
### What's done:
1) Added wrappers to call kaml in more elegant way
2) Added tests and documentation

### CODE REVIEW

**Comment by akuleshov7** [comment]
@charleskorn hey, what do you think about that?

**Comment by charleskorn** [comment]
Hi @akuleshov7, thanks for the PR.

I'm not sure including this is a good idea. The documentation for [`serializer()`](https://github.com/Kotlin/kotlinx.serialization/blob/ef53d75/core/commonMain/src/kotlinx/serialization/Serializers.kt#L106) warns against using it: 

> This method uses platform-specific reflection available for the given erased `KClass` and is not recommended to use this method for anything, but last-ditch resort

I'd prefer that anyone who really wants to use this shortcut have to add an extension function themselves and understand the implications of what they're doing.

**Comment by akuleshov7** [comment]
@charleskorn but you suggest to use `serializer()` directly in the readme: 
```
val result = Yaml.default.decodeFromString(Team.serializer(), input)
```

There are no other ways to call kaml application without calling serializer()

**Comment by charleskorn** [comment]
Hi @akuleshov7, there are multiple different implementations of `serializer()`.

When you use something like `Team.serializer()`, this is resolved at compile time and works on all platforms. The compiler will report an error if the type doesn't support serialization and compilation will fail.

When you use the `KClass` extension method `serializer()`, as this PR does, the serializer is resolved at runtime, which has all the limitations discussed in [the documentation for that extension method](https://github.com/Kotlin/kotlinx.serialization/blob/ef53d75/core/commonMain/src/kotlinx/serialization/Serializers.kt#L106). If the serializer can't be determined at runtime, an exception is thrown.

**Comment by akuleshov7** [comment]
Got it, ok.

**Pull request closed without merging**
